config/routes.rb
Rails.application.routes.draw do

  mount API::Base, at: "/"

  scope "(:locale)", locale: /en|vi/ do
    # static_pages
    root "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    # users
    get "/signup", to: "users#new"
    get ":id/following", to: "following#index", as: "following"
    get ":id/follower", to: "follower#index", as: "follower"
    resources :users, except: :new
    # sessions
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    #account_activations
    resources :account_activations, only: :edit
    #password__resets
    resources :password_resets, except: %i(show index destroy)
    #microposts
    resources :microposts, only: %i(create destroy)
    #relationship
    resources :relationships, only: %i(create destroy)
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize object.errors.count, "error" %>.
    </div>
    <ul>
      <% object.errors.messages.each do |key, value| %>
        <li><%= [t(key), value].join(" ") %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= paginate @feed_items, theme: "twitter-bootstrap-3",
    params: { controller: :static_pages, action: :home } %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: t("compose_post") %>
  </div>
  <span class="image">
    <%= f.file_field :image, accept: Settings.image_accept %>
  </span>
  <%= f.submit t("post"), class: "btn btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_path @user %>">
    <strong id="following" class="stat">
      <%= @user.following.size %>
    </strong>
    <%= t "following" %>
  </a>
  <a href="<%= follower_path @user %>">
    <strong id="followers" class="stat">
      <%= @user.followers.size %>
    </strong>
    <%= t "followers" %>
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: Settings.micropost_size), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to t("view_my_profile"), current_user %></span>
<span><%= pluralize current_user.microposts.size, t("micropost") %></span>