config/routes.rb
Rails.application.routes.draw do

  mount API::Base, at: "/"

  scope "(:locale)", locale: /en|vi/ do
    # static_pages
    root "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    # users
    get "/signup", to: "users#new"
    get ":id/following", to: "following#index", as: "following"
    get ":id/follower", to: "follower#index", as: "follower"
    resources :users, except: :new
    # sessions
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    #account_activations
    resources :account_activations, only: :edit
    #password__resets
    resources :password_resets, except: %i(show index destroy)
    #microposts
    resources :microposts, only: %i(create destroy)
    #relationship
    resources :relationships, only: %i(create destroy)
  end
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  FORMAT_IMG = Settings.format_img.freeze
  MICROPOST_PARAMS = Settings.micropost_params.freeze

  belongs_to :user
  has_one_attached :image

  validates :user_id, :content, presence: true,
    length: {maximum: Settings.content_post_length}
  validates :image, content_type: {in: FORMAT_IMG, message: I18n.t("micropost_mess1")},
    size: {less_than: Settings.mega_size.megabytes, message: I18n.t("micropost_mess2")}

  scope :recent_posts,->{order created_at: :desc}
  scope :feed_user,-> following_ids{where user_id: following_ids}
end

app/controllers/api/entities/micropost.rb
module API
  module Entities
    class Micropost < Grape::Entity
      expose :id
      expose :content
    end
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: %i(create destroy)
  before_action :correct_user, only: :destroy

  def create
    @micropost = current_user.microposts.build micropost_params
    @micropost.image.attach micropost_params[:image]
    if @micropost.save
      flash[:success] = t "micropost_created"
      redirect_to root_url
    else
      @feed_items = current_user.feed.page(params[:page]).per Settings.pagination
      render "static_pages/home"
    end
  end

  def destroy
    if @micropost.destroy
      flash[:success] = t "micropost_deleted"
      redirect_to request.referer || root_url
    else
      flash[:danger] = t "micropost_deleted_fails"
      redirect_to root_url
    end
  end

  private

  def micropost_params
    params.require(:micropost).permit Micropost::MICROPOST_PARAMS
  end

  def correct_user
    @micropost = current_user.microposts.find_by id: params[:id]
    redirect_to root_url unless @micropost
  end
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: Settings.micropost_size),
    micropost.user %>
  <span class="user">
    <%= link_to micropost.user.name, micropost.user %>
  </span>
  <span class="content">
    <%= micropost.content %>
    <%= image_tag micropost.image if micropost.image.attached? %>
  </span>
  <span class="timestamp">
    <%= t("posted") %> <%= time_ago_in_words micropost.created_at %>
      <%= t("ago") %>
    <% if current_user? micropost.user %>
      <%= link_to t("delete"), micropost_path(micropost.id), method: :delete,
      data: {confirm: t("you_sure")} %>
    <% end %>
  </span>
</li>