config/routes.rb
Rails.application.routes.draw do

  mount API::Base, at: "/"

  scope "(:locale)", locale: /en|vi/ do
    # static_pages
    root "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    # users
    get "/signup", to: "users#new"
    get ":id/following", to: "following#index", as: "following"
    get ":id/follower", to: "follower#index", as: "follower"
    resources :users, except: :new
    # sessions
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    #account_activations
    resources :account_activations, only: :edit
    #password__resets
    resources :password_resets, except: %i(show index destroy)
    #microposts
    resources :microposts, only: %i(create destroy)
    #relationship
    resources :relationships, only: %i(create destroy)
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to t("tutorial"), Settings.link.news_link %>
    <%= t "by" %>
    <%= link_to t("author"), Settings.link.author_link %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t("about"), about_path %></li>
      <li>
        <%= link_to t("news"), Settings.link.news_link %>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("title"), root_path, id: "logo" %>
    <div class="locale_change">
      <%= link_to image_tag("co_anh.jpg", class: "co_anh"),
        locale: :en, id: "en" %>
      <%= link_to image_tag("co_viet_nam.jpeg", class: "co_viet_nam"),
        locale: :vi, id: "vi" %>
    </div>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("home"), root_path %></li>
        <li><%= link_to t("help"), help_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <%= link_to current_user.name, users_path,
              class: "dropdown-toggle", "data-toggle": "dropdown" %>
            <ul class="dropdown-menu">
              <li><%= link_to t(".profile"), current_user %></li>
              <li><%= link_to t(".settings"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li> <%= link_to t("logout"), logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("login"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>

  
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
  <%= render "layouts/header" %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </div>
  </body>
</html>